#!/bin/sh

# Change i3 mod key in config and reload i3

ALT="Mod1"
SUPER="Mod4"

conf="$HOME/.config/i3/config"
currmod=$(grep "set \$mod" $conf | awk '{print $NF}')

if [ "$currmod" = "$SUPER" ]; then
    currmod="Super"
elif [ "$currmod" = "$ALT" ]; then
    currmod="Alt"
else
    currmod="Unknown"
fi

choice="$(echo "Super,Alt" | rofi -i -sep ',' -dmenu -p "Change mod (set $currmod)")"

if [ "$choice" = "Win" ]; then
    modkey="$SUPER"
elif [ "$choice" = "Alt" ]; then
    modkey="$ALT"
else
    modkey="$SUPER"
fi

sed -i "s/\(set \$mod\)\(.*\)/\1 $modkey/" ~/.config/i3/config
i3-msg reload

