#!/bin/sh

DEST="/media/flo/backup/archlinux-laptop-home-backup/"
LOG="/tmp/$$_$(date +%d-%m-%Y-%H:%M:%S)_backup"

echo "Temporary log can be found here: ${LOG}"

if [ ! -d $DEST ]; then
	echo "Backup directory does not exist or could not be found. Check out the log file." | tee ${LOG}
	exit 1
else
	echo "Starting backup..."
	if rsync -avzrP --delete $HOME/cloud $HOME/.config "${DEST}" > ${LOG} 2>&1; then
		echo "Backup successful."
		exit 0
	else 
		echo "Error occured during backup. Check out the log file."
		exit 1
	fi
fi

