#!/bin/sh
    
ALT="Mod1"
SUPER="Mod4"
conf="$HOME/.config/i3/config"

i3status | while :
do
    read line
    modkey=$(grep "set \$mod" $conf | awk '{print $NF}')
    if [ "$modkey" = $SUPER ]; then
        modstr="Super"
    elif [ "$modkey" = $ALT ]; then
        modstr="Alt"
    else
        modstr="Unknown"
    fi
    echo "Mod: $modstr | $line" || exit 1
done
