#!/bin/sh

# Simple dmenu power menu

DMENU='dmenu -fn IBMPlexMono:semibold:size=12 -nb #000000 -p Power:'
choice=$(echo -e "sleep\nlogout\nreboot\nshutdown" | $DMENU)

case "$choice" in
	sleep) ~/cloud/Linux/scripts/sleeplock ;;
	logout) killall dwm ;;
	reboot) reboot ;;
	shutdown) shutdown now ;;
esac
